vim.g.terminal_emulator="/bin/bash"
--init.lua
require "keymaps"
require "lazy-config"
require "options"
require "lsp-config"
require "rust-tools-config"
require "alpha-config"
require "nvim-neo-tree-config"
require "hop-config"
require "lualine-config"
require "telescope-config"
require "treesitter-config"
require "toggleterm-config"
require "bufferline-config"
require "undotree-config"
require "git-config"
require "whichkey"
require "diff"
require "aerial-config"
require "cscope-config"
require "ssh-config"
