vim.g.terminal_emulator="zsh"
-- init.lua
require "keymaps"
require "lazy-config"
require "options"
require "lsp-config"
require "alpha-config"
require "hop-config"
require "lualine-config"
require "telescope-config"
require "treesitter-config"
require "toggleterm-config"
require "bufferline-config"
require "undotree-config"
require "git-config"
require "whichkey"
